Feat: TablePress importer
Automattic/newspack-custom-content-migrator pull request #145
Opened 2022-03-16 11:34 UTC by kariae

This PR introduces a bulk tables importer to TablePress. It accepts CSV and JSON files from a given folder.

It uses the filename as the table name and the first row of data as the table header (same as the GUI importer of TablePress).

Since the import command uses the internal classes/methods of the plugin TablePress, the plugin should be installed before using it.

Below some examples to use the command line:

```bash
# Import bulk CSV tables from /tmp folder.
wp newspack-content-migrator import-table-press-tables --input-dir=/tmp
# Import bulk JSON tables from /tmp folder.
wp newspack-content-migrator import-table-press-tables --input-dir=/tmp --input-type=json
```

The code introduces a new migrator logic class so it need a review 🙇

2022-03-16 13:47 UTC, iuravic requested changes

2022-03-16 13:47 UTC, iuravic commented on src/MigrationLogic/TablePress.php
> +			// TablePress is a dependency, and will have to be installed before the public functions/commands can be used.
This comment explains everything 👍  Similar to [the comment I left](https://github.com/Automattic/newspack-custom-content-migrator/pull/144#pullrequestreview-911650339) for the NinjaPress exporter PR, could we also add a validation check to the `cmd_import_table_press` method to check if the dependency is installed?

2022-03-16 13:47 UTC, iuravic commented on src/MigrationLogic/TablePress.php
> +		$importer->setAccessible( true );
Behold the power of PHP :)

2022-03-16 15:50 UTC, kariae commented on src/MigrationLogic/TablePress.php
> +			// TablePress is a dependency, and will have to be installed before the public functions/commands can be used.
Thanks @iuravic for the quick review and for noticing this 👍

2022-03-16 15:51 UTC, kariae commented on src/MigrationLogic/TablePress.php
> +			// TablePress is a dependency, and will have to be installed before the public functions/commands can be used.
Thanks @iuravic for the quick review and for noticing this 👍

2022-03-18 14:32 UTC, iuravic approved these changes

2022-03-18 14:56 UTC, merged