Add/split guest author
Automattic/newspack-custom-content-migrator pull request #146
Opened 2022-03-22 14:17 UTC by eddiesshop

Takes a guest author string as the first argument. All posts that guest author has been associated with will then get reassigned to whatever new guest authors have been supplied to be created.

2022-03-23 18:11 UTC, iuravic requested changes
Looks great, and could come in really handy! Thanks for making this into a reusable command!

I left just a couple of very small notes here.

2022-03-23 18:11 UTC, iuravic commented on src/Migrator/General/CoAuthorPlusMigrator.php
> +						'description' => "The new guest author's to create (delimited values accepted). The original will be disassociated.",
Ah, so the command will create the new GAs, too. Very nice! I see it in the code now after reading this, but it helped a lot that it's stated in this description. Thanks!

Let's please add an example to the end of this "description" sentence, too. I'd suggest adding both an example for multiple GAs and for a single GA, just to demonstrate the power of this command a bit more.

2022-03-23 18:11 UTC, iuravic commented on src/Migrator/General/CoAuthorPlusMigrator.php
> +						'description' => 'Delimiter to use to split new-guest-authors values.',
I wonder would it have made sense the delimiter was standardized, like if we used a comma? Perhaps that way:
- we wouldn't need this parameter,
- we could say that the `new-guest-author-names` is CSV

2022-03-23 18:11 UTC, iuravic commented on src/Migrator/General/CoAuthorPlusMigrator.php
> +		$guest_author_posts = "SELECT tr.* FROM $wpdb->term_relationships tr
Let's use `$wpdb->prepare` to prepare the SQL parameter `$old_guest_author`, please, to prevent SQL injection.

It's a very far fetched case that this could be misused, since we use it for our local work internally, but `$wpdb->prepare` is so handy and we can rest easy :)

2022-03-23 18:11 UTC, iuravic commented on src/Migrator/General/CoAuthorPlusMigrator.php
> +			$guest_author = ( new CoAuthors_Guest_Authors() )->get_guest_author_by( 'id', $author_id );
This is perfectly fine, just sharing that alternatively we could have used `$this->coauthorsplus_logic->coauthors_guest_authors` since that's already an instantiated [public property in the `$this->coauthorsplus_logic`](https://github.com/Automattic/newspack-custom-content-migrator/blob/master/src/MigrationLogic/CoAuthorPlus.php#L41). But this works well just the same!

2022-03-23 20:03 UTC, eddiesshop commented on src/Migrator/General/CoAuthorPlusMigrator.php
> +				'shortdesc' => 'Used to take a guest author and split to multiple different guest authors the user specifies',
Great, thanks for suggestion!

2022-03-23 20:14 UTC, eddiesshop commented on src/Migrator/General/CoAuthorPlusMigrator.php
> +						'description' => 'Delimiter to use to split new-guest-authors values.',
I'd like to leave it as-is, I really meant for this to be a one-off command that we can run from the CLI. If we need to add some mass update functionality, we can update this to support a CSV.

2022-03-23 20:16 UTC, eddiesshop commented on src/Migrator/General/CoAuthorPlusMigrator.php
> +		$guest_author_posts = "SELECT tr.* FROM $wpdb->term_relationships tr
Updated!

2022-03-23 20:18 UTC, eddiesshop commented on src/Migrator/General/CoAuthorPlusMigrator.php
> +			$guest_author = ( new CoAuthors_Guest_Authors() )->get_guest_author_by( 'id', $author_id );
Thanks! Updated.

2022-03-24 14:39 UTC, iuravic requested changes

2022-03-24 14:39 UTC, iuravic commented on src/Migrator/General/CoAuthorPlusMigrator.php
> +				'shortdesc' => 'Reassigns all posts currently associated to a specific Guest Author to different multiple (or single) Guest Author(s)',
Let's please update this description to the following:
```
Reassigns all posts currently associated to a specific Guest Author to different multiple (or single) Guest Author(s). Example use: `wp newspack-content-migrator co-authors-split-to-multiple-coauthors "Chris Christofersson of NewsSource, with Adam Black of 100 Days in Appalachia" --new-guest-author-names="Chris Christofersson; Adam Black of 100 Days in Appalachia" --delimiter="; "
```

2022-03-31 17:52 UTC, merged