Feat/add new orleans tribune migrator
Automattic/newspack-custom-content-migrator pull request #158
Opened 2022-05-20 12:52 UTC by kariae

A migrator of WPPA albums to Jetpack Slideshow Block, this is set for one publisher, but can ve easily refactored later to be used for other publishers.

2022-05-26 14:52 UTC, iuravic approved these changes
It would be great if we had this in a reusable form, @kariae :) Do you think it would be much effort to extract it into a reusable migrator?

2022-05-27 17:17 UTC, kariae commented
@iuravic I add the possibility to handle many albums' shortcodes within the same post content and set this as general migratory. The tests on the publisher content were successful.

2022-05-27 17:29 UTC, iuravic requested changes

2022-05-27 17:29 UTC, iuravic commented on src/Migrator/General/PhotoAlbumsMigrator.php
> +class PhotoAlbumsMigrator implements InterfaceMigrator {
Looks amazing! 💯 💯 💯 ! 🥳 !
Just one thing, could we please rename `PhotoAlbumsMigrator` to something just a tiny bit more descriptive, like `PhotoAlbumProGalleryMigrator`?

2022-05-27 17:37 UTC, iuravic approved these changes

2022-05-30 06:38 UTC, merged