newsroom.co.nz custom migrator
Automattic/newspack-custom-content-migrator pull request #163
Opened 2022-05-31 16:24 UTC by iuravic

Reads postmeta saved by the Scraper Migrator Plugin, and turns it into the actual data that it should be.

2022-05-31 22:33 UTC, kariae requested changes

2022-05-31 22:33 UTC, kariae commented on src/Migrator/PublisherSpecific/NewsroomCoNzMigrator.php
> +				$d=1;
I guess we can add a log here instead. That's said, I'm not sure about the use case here, but we can create the co-authors without their bio and avatars, as long as we do have the at least the author name, does it make sense to just remove the condition?

2022-05-31 22:33 UTC, kariae commented on src/Migrator/PublisherSpecific/NewsroomCoNzMigrator.php
> +				if ( true === str_contains( $original_url, $cat_url ) ) {
str_contains is a PHP8 feature, while the Atomic servers are still on 7.4, so this will break once executed there. I had to create a polyfill for this function (and others) since their use for other migratory, so I wonder if we can start the talk about migration to PHP 8?

2022-05-31 22:33 UTC, kariae commented on src/Migrator/PublisherSpecific/NewsroomCoNzMigrator.php
> +			$original_url_parsed = parse_url( $original_url );
I believe the permalink migration is working, can you, please, add an example(as a comment) of the possible $original_url value, as I tried with a live URL of a post from the live site, and I had an error, I probably get the wrong URL format.

2022-05-31 22:33 UTC, kariae commented on src/Migrator/PublisherSpecific/NewsroomCoNzMigrator.php
> +				$d=1;
Same. we can add a log here :)

2022-05-31 22:33 UTC, kariae commented on src/Migrator/PublisherSpecific/NewsroomCoNzMigrator.php
> +		// Clean up empty categories.
Is this a TODO?

2022-06-01 09:51 UTC, iuravic commented on src/Migrator/PublisherSpecific/NewsroomCoNzMigrator.php
> +				$d=1;
@kariae you're absolutely right, I fully agree with your remakrs if this was production code 👍  No need for these kinds of loops, they're messy.

The reason I left these helper snippets it is that I'll be the only one running this migrator (Publisher's LE), and it's a two-time job, so I've felt free to leave these helper snippets which make my workflow more efficient. Specifically, here I use step debugging, and these else-s are here for that purpose.

So, here's my question -- for PublisherSpecific Migrators, are we to review just the effect our code has on the Atomic infrastructure (the MySQL restrictions) and make sure it doesn't overload an Atomic machine, or should we start reviewing PublisherSpecific code as actual production code and do full reviews?

I'm absolutely OK with us doing either of these, and think that we should decide as a Team. I personally would vote that we keep this review arrangement:
- general and reusable code -- we review fully with two goals in mind: to make sure impact on the platform is OK, and that the code is completely in line with our best practices and standards,
- PublisherSpecific -- we just review impact on Platform, and let the LE merge at their convenience.

2022-06-01 09:59 UTC, iuravic commented on src/Migrator/PublisherSpecific/NewsroomCoNzMigrator.php
> +			$original_url_parsed = parse_url( $original_url );
Oh, so you mean the permalink migration is built into the Scraper? 😮

2022-06-01 10:00 UTC, iuravic commented on src/Migrator/PublisherSpecific/NewsroomCoNzMigrator.php
> +		// Clean up empty categories.
Yes, exactly. For now I just imported the first 50 demo posts for the Publisher to review. They're not yet onboarded to Newspack, so I wanted to leave all the cats for dev purposes. If they agree they will join Newspack, I'll do an actual scrape and fill in this bit.

2022-06-01 10:11 UTC, kariae commented on src/Migrator/PublisherSpecific/NewsroomCoNzMigrator.php
> +				if ( true === str_contains( $original_url, $cat_url ) ) {
TIL, thank you for sharing the info, Ivan.

2022-06-01 11:37 UTC, merged