feat: prevent content-diff from erroneously declaring no posts to refresh.
Automattic/newspack-custom-content-migrator pull request #192
Opened 2022-08-17 02:16 UTC by eddiesshop

This body of work will detect if table collations are different between live and core WP DB tables. If they are, this work will be able to execute a set of instructions to correct the discrepancy. This will then allow the content-diff to proceed correctly.

2022-08-19 09:22 UTC, iuravic requested changes

2022-08-19 09:22 UTC, iuravic commented on src/MigrationLogic/ContentDiffMigrator.php
> +		if ( ! $this->are_table_collations_matching( $live_table_prefix ) ) {
Sorry if I'm getting this wrong, just double checking -- won't this always throw an exception? Because [this expression](https://github.com/Automattic/newspack-custom-content-migrator/pull/192/files#diff-318440e2d6c2a49e7dc183f0e2590ace80e9984dff1602b43286cfc85eca0133R1522) seems to me would always be true since `$this->validated_collation_tables` was never set in [cmd_search_new_content_on_live](https://github.com/Automattic/newspack-custom-content-migrator/blob/009d16ef5f1c172c8038879a752706625dfe1376/src/Migrator/General/ContentDiffMigrator.php#L241)?

If that's the case (sorry if it's not), we should probably just add a line before [this one](https://github.com/Automattic/newspack-custom-content-migrator/blob/009d16ef5f1c172c8038879a752706625dfe1376/src/Migrator/General/ContentDiffMigrator.php#L253), and do something like:
```
$validated_collation_tables = self::$logic->get_validated_collation_tables( $different_tables_only );
```
and probably do that [in this try here](https://github.com/Automattic/newspack-custom-content-migrator/blob/009d16ef5f1c172c8038879a752706625dfe1376/src/Migrator/General/ContentDiffMigrator.php#L246) where DB validation is being made,

then [call the `get_live_diff_content_ids`](https://github.com/Automattic/newspack-custom-content-migrator/blob/009d16ef5f1c172c8038879a752706625dfe1376/src/Migrator/General/ContentDiffMigrator.php#L253) with $validated_collation_tables as another argument:
```
$ids = self::$logic->get_live_diff_content_ids( $live_table_prefix, $validated_collation_tables );
```

2022-08-19 09:22 UTC, iuravic commented on src/Migrator/General/ContentDiffMigrator.php
> +		$tables_with_differing_collations = self::$logic->get_validated_collation_tables( true );
And lastly, proposing that we used local variable:
```
$validated_collation_tables = self::$logic->validate_collation_on_content_diff_tables( $live_table_prefix, $skip_tables );
$tables_with_differing_collations = self::$logic->get_validated_collation_tables( $validated_collation_tables, true );
```

2022-08-19 09:22 UTC, iuravic commented on src/MigrationLogic/ContentDiffMigrator.php
> +	public function get_validated_collation_tables( bool $diff_collations_only = false ): array {
If this method "filters" the `$validated_collation_tables` data, perhaps we could call it `filter_validated_collation_tables` (or something), and if `validate_collation_on_content_diff_tables` fetches the data, perhaps we could call it `get_validated_collation_tables` instead.

2022-08-22 20:18 UTC, eddiesshop commented on src/MigrationLogic/ContentDiffMigrator.php
> +	private ?array $validated_collation_tables = null;
This has been removed.

2022-08-22 20:19 UTC, eddiesshop commented on src/MigrationLogic/ContentDiffMigrator.php
> +		return $this->validated_collation_tables = $validated_tables;
This function has been removed.

2022-08-22 20:21 UTC, eddiesshop commented on src/MigrationLogic/ContentDiffMigrator.php
> +			return array_filter( $this->validated_collation_tables, fn( $validated_table ) => false === $validated_table['match_bool'] );
I opted to instead have a call to the function which obtains the list of tables and their collation status. I did this because it would be assumed that the structure of the array returned from that call would be known. The same could not be guaranteed by accepting `$validated_collation_tables` as input.

2022-08-22 20:22 UTC, eddiesshop commented on src/MigrationLogic/ContentDiffMigrator.php
> +		return $this->validated_collation_tables;
This function no longer returns the instance variable.

2022-08-22 20:23 UTC, eddiesshop commented on src/MigrationLogic/ContentDiffMigrator.php
> +		if ( empty( $this->validated_collation_tables ) ) {
I opted to call the function which obtains the collation comparison list instead since it would be a known data structure, as opposed to accepting it as input, whose structural integrity cannot be guaranteed.

2022-08-22 20:24 UTC, eddiesshop commented on src/MigrationLogic/ContentDiffMigrator.php
> +		return empty( $this->get_validated_collation_tables( true ) );
I opted to call the function which obtains the collation comparison list instead since it would be a known data structure, as opposed to accepting it as input, whose structural integrity cannot be guaranteed.

2022-08-22 20:24 UTC, eddiesshop commented on src/MigrationLogic/ContentDiffMigrator.php
> +			$this->validate_collation_on_content_diff_tables( $table_prefix, $skip_tables );
This function has been updated to match suggestion above.

2022-08-22 20:27 UTC, eddiesshop commented on src/MigrationLogic/ContentDiffMigrator.php
> +		if ( ! $this->are_table_collations_matching( $live_table_prefix ) ) {
Yes you're right, oversight on my part.

Because of the modifications to make these function calls stateless, this is no longer the case.

2022-08-22 20:28 UTC, eddiesshop commented on src/Migrator/General/ContentDiffMigrator.php
> +		$tables_with_differing_collations = self::$logic->get_validated_collation_tables( true );
Local variables are now used 👍

2022-08-22 20:28 UTC, eddiesshop commented on src/MigrationLogic/ContentDiffMigrator.php
> +	public function get_validated_collation_tables( bool $diff_collations_only = false ): array {
Updated the function name to reflect that it is filtering.

2022-08-24 15:47 UTC, iuravic approved these changes

2022-08-24 15:48 UTC, merged