feat(attachment): add command to verify broken images URLs
Automattic/newspack-custom-content-migrator pull request #202
Opened 2022-08-31 11:15 UTC by kariae

This PR adds a command to use the Attachments utility method `get_broken_attachment_urls_from_posts` to get broken in-story image URLs.

The method was not checking [the responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) using the`srcset` attribute from the `<img>` tag, this is fixed now.

The command can be used in batches to run it multiple times in parallel when the number of posts to check is high. It also accepts an `index` parameter in case the command is killed and you need to restart it from the last index.

I added a parameter to the `get_broken_attachment_urls_from_posts` method called `$logger` which is a callback function that we can use while looping over the posts, a use case for it, is to pass a function that will log the missing images in the post while looping over all the posts without waiting for the loop to end.

2022-08-31 11:24 UTC, iuravic requested changes
Everything looks great! Amazing job, and an amazing script! If we could just make that one private function public, that's all the comments I have.

2022-08-31 11:24 UTC, iuravic commented on src/MigrationLogic/Attachments.php
> +	private function get_responsive_images_sources_from_content( $post_content ) {
Could we make this function public? It might be useful for some other Migrators in the future to access too.

2022-09-01 12:21 UTC, kariae commented on src/MigrationLogic/Attachments.php
> +	private function get_responsive_images_sources_from_content( $post_content ) {
Yup, that's a good idea. Actually, this method gets only the responsive images from the post content, I refactored the code a bit to get all the images from the post content using this method (using the `src` attribute and the responsive images), that works for you?

2022-09-07 08:51 UTC, iuravic approved these changes

2022-09-07 09:39 UTC, merged