Add reusable Simple Local Avatars logic
Automattic/newspack-custom-content-migrator pull request #211
Opened 2022-09-16 03:48 UTC by abdelmalekkkkk

2022-09-16 07:37 UTC, iuravic requested changes

2022-09-16 07:37 UTC, iuravic commented on src/MigrationLogic/SimpleLocalAvatars.php
> +        $this->simple_local_avatars->assign_new_user_avatar( (int) $attachment_id, $user_id );
Could you run PHPCS on this file? We at least want the indentations to be the same. Thanks!

As a rule, we need to run PHPCS on all general and reusable code, and you don't have to run it on publisher specific ones.
But please still set the indentations in your IDE to use tabs -- this is what the whole A8C WP community uses and that's why we have tabs in our Sniffer standards.

2022-09-16 07:37 UTC, iuravic commented on src/MigrationLogic/SimpleLocalAvatars.php
> +		if ( is_file( $simple_local_avatars_plugin_file ) && include_once $simple_local_avatars_plugin_file ) {
Could we perhaps add a simple method to make it easy for us to check if SLA is on?
For example:
```
public function is_sla_plugin_active() {
    return $this->sla_logic->simple_local_avatars != null;
}
```

The command below runs the method `cmd_lkldnow_migrate_avatars` which checks for it like this
```
if ( $this->sla_logic->simple_local_avatars == null ) {
```
but if you're using `$this->sla_logic` for the first time, it would be much easier if there was a public method `is_sla_plugin_active` instead of reading its code and figuring out that the constructor might leave it null if the plugin file is not found.

2022-09-16 09:12 UTC, iuravic commented
Added the whole Launch Team as reviewers.

2022-09-16 15:42 UTC, abdelmalekkkkk commented on src/MigrationLogic/SimpleLocalAvatars.php
> +        $this->simple_local_avatars->assign_new_user_avatar( (int) $attachment_id, $user_id );
My bad. My editor switched to using spaces for some reason. I fixed that.

2022-09-16 15:42 UTC, abdelmalekkkkk commented on src/MigrationLogic/SimpleLocalAvatars.php
> +		if ( is_file( $simple_local_avatars_plugin_file ) && include_once $simple_local_avatars_plugin_file ) {
Good point. I added the is_sla_plugin_active method. Thanks!

2022-09-19 09:50 UTC, iuravic requested changes

2022-09-19 09:50 UTC, iuravic commented on src/MigrationLogic/SimpleLocalAvatars.php
> +	public function is_sla_plugin_active() {
@abdelmalekkkkk the PHPCS still reports errors on this file. Here's how you can run PHPCS:

![image](https://user-images.githubusercontent.com/29167323/190991940-6145c26d-9243-47f7-a567-31bbef4d449c.png)

Ideally good IDE integration should fix these automatically. But until you set that up, follow these errors one by one, and fix them manually until they're all gone.

Also running `./vendor/bin/phpcbf --standard=phpcs.xml src/MigrationLogic/SimpleLocalAvatars.php` will fix all the errors automatically which can be fixed that way. The remaining errors you need to fix automatically.

And we should be doing this on all reusable code.

2022-09-19 20:40 UTC, abdelmalekkkkk commented on src/MigrationLogic/SimpleLocalAvatars.php
> +	public function is_sla_plugin_active() {
Thank for pointing this out. I think I messed up the PHPDocs enough to never do it again 😄

Fixed!

2022-09-19 20:41 UTC, abdelmalekkkkk commented
@iuravic Thanks for the review. I made the requested changes and merged this to master, since I need it for [this Baltimore task](https://app.asana.com/0/1201792624707312/1202703102746936).

2022-09-19 20:41 UTC, merged