add revision cleaning commands
Automattic/newspack-custom-content-migrator pull request #218
Opened 2022-09-27 21:05 UTC by leogermani

2022-09-27 22:39 UTC, gamebits commented
Will any of the tools in this package be useful? https://github.com/trepmal/wp-revisions-cli

2022-09-28 11:22 UTC, leogermani commented
> Will any of the tools in this package be useful? https://github.com/trepmal/wp-revisions-cli

The issue is that those commands will not take our limitations into account. It will either clean all revisions in one big SQL statement or loop through them very quickly...

2022-09-28 15:24 UTC, iuravic requested changes

2022-09-28 15:24 UTC, iuravic commented on src/Migrator/General/PostsMigrator.php
> +		WP_CLI\Utils\format_items( $format, $results, [ 'post_ID', 'num_of_revisions' ] );
Instead of outputting to the STDOUT, should we instead save the IDs to a log file? I would assume we'd be working with 10s of thousands of posts in real life, or even 100s of thousands, so perhaps output to STDOUT might not be super efficient.

For example, we might do something like this -- code completely untested :) :
```
const LOG_POST_IDS_WITH_MANY_REVISIONS = 'posts_w_many_revisions.log';

...

public function cmd_find_posts_by_number_of_revisions( $args, $assoc_args ) {
  ...

  foreach ( $results as $key => $result ) {
    file_put_contents(
      self::LOG_POST_IDS_WITH_MANY_REVISIONS,
      ( $key > 0 ? "," : '' ) . $result->post_ID,
      FILE_APPEND
    );
  }

  WP_CLI::success( sprintf( "Done. Post IDs saved to CSV file %s". self::LOG_POST_IDS_WITH_MANY_REVISIONS ) );
```

In this case perhaps we can remove the `format` argument from the CLI command completely.

2022-09-28 15:24 UTC, iuravic commented on src/MigrationLogic/Posts.php
> +	 * @return integer
This probably returns a string, not an integer?

2022-09-28 15:24 UTC, iuravic commented on src/Migrator/General/PostsMigrator.php
> +		WP_CLI::add_command(
Also, please run PHPCS on this, thanks!

```
```
./vendor/bin/phpcs --standard=phpcs.xml src/Migrator/General/PostsMigrator.php
```

2022-09-28 18:01 UTC, leogermani commented on src/Migrator/General/PostsMigrator.php
> +		$number  = intval( $positional_args[1] );
I see no harm in the change. Will do it

2022-09-28 18:02 UTC, leogermani commented on src/Migrator/General/PostsMigrator.php
> +		WP_CLI\Utils\format_items( $format, $results, [ 'post_ID', 'num_of_revisions' ] );
That's something I'd like to see in real world. I don't think it will be 10s of thousands of posts because we will only be handling posts with hundreds of revisions, this should be just a small part of all posts in a site. But that's just a hypothesis

2022-09-28 18:04 UTC, leogermani commented on src/Migrator/General/PostsMigrator.php
> +				'default'     => 50,
Now we are talking!

2022-09-28 18:05 UTC, leogermani commented on src/Migrator/General/PostsMigrator.php
> +				'default'     => 1000,
it was not a typo. As I have no idea what the limitations are I was taking the advice to start slow and test the limits with caution.

Start with 50 revisions being deleted and sleeping for a whole second.

And then tweak the values from there. But you know better what our servers like

2022-09-28 19:40 UTC, leogermani commented on src/Migrator/General/PostsMigrator.php
> +		$number  = intval( $positional_args[1] );
done

I just left `newspack-content-migrator find-posts-by-number-of-revisions [$number_of_revisions=500]` as it is.

When it receives only one argument, like this, I think it's fine.

2022-09-28 19:42 UTC, leogermani commented on src/Migrator/General/PostsMigrator.php
> +			array(
sure, but I just followed what's been used in the file

2022-09-28 19:42 UTC, leogermani commented on src/Migrator/General/PostsMigrator.php
> +				'default'     => 50,
done

2022-09-28 19:44 UTC, leogermani commented on src/MigrationLogic/Posts.php
> +	 * @return integer
you're right, typecasting it now

2022-09-29 08:36 UTC, iuravic commented on src/Migrator/General/PostsMigrator.php
> +			array(
Makes perfect sense, of course, and thanks. Until recently we had a code sniffer rule which said use of long array syntax was mandatory, but it was recently removed.

2022-09-29 08:36 UTC, iuravic commented on src/Migrator/General/PostsMigrator.php
> +				'default'     => 1000,
Gotcha 👍

2022-09-29 08:39 UTC, iuravic commented
@leogermani your changes look great! Did you want to keep working on it some more, or is it ready to be merged now?

Once you'd like a final "👍" just please click "re-request review", and we'll merge this wholesome & fine code.

2022-09-29 13:42 UTC, leogermani commented
@iuravic I think we can consider this a good first version

I'm curious to run the script to find posts with too many revisions, and then test the cleanup scripts and see if they are what we need

2022-11-15 10:28 UTC, iuravic approved these changes

2022-11-21 17:18 UTC, merged