Add/saporta report migrator
Automattic/newspack-custom-content-migrator pull request #270
Opened 2023-03-06 14:08 UTC by kariae

This PR introduces the Saporta Report migrator and some internal tooling improvements. Some Commits that need some code review, please:

2023-03-06 14:29 UTC, iuravic requested changes

2023-03-06 14:29 UTC, iuravic commented on src/Logic/GutenbergBlockGenerator.php
> + * Class ContentDiffMigrator and main logic.
Could we perhaps add a short bullet-list type instructions in the class comment, or somewhere else, which describes how we can create new methods, please? Something like,
"To add new block methods:
- create a draft post in Gutenberg and add the desired block
- copy the source HTML, and paste it in a new method...
- use something ... e.g. should the new method return `get_block_json_array_from_content()` in some way?
- or use the WP block functions in some of these steps...

These steps ☝️ are all wrong for sure 😅 , it would just be awesome if we had a simple reminder how to use and/or add new methods 🙇

2023-03-06 14:29 UTC, iuravic commented on src/Logic/GutenbergBlockGenerator.php
> +                            return null;
Do you think it would be useful to save a list of not found IDs in a log file? Just asking for your opinion. Perhaps not, if we save the whole output when running the command? Or perhaps we could add a log file name const and just log all such errors with `$this->logger->log()`?

Same for,
- `get_jetpack_slideshow()` , "Attachment %d doesn't exist!"

2023-03-06 14:29 UTC, iuravic commented on src/Utils/Logger.php
>  		$message .= "\n";
This is something left over from a previous commit, but this "\n" ends up in WP_CLI::log too, and causes a double line break.

Could we please clean this up and:
- remove this line,
- then WP_CLI::log will only output this in a new line nicely
- and then add the "\n" to file_put_contents, like `file_put_contents( $file, "\n" . $message, FILE_APPEND );`

Thank you!

2023-03-06 15:25 UTC, kariae commented on src/Logic/GutenbergBlockGenerator.php
> +                            return null;
Yup, it makes sense, I'll add that.

2023-03-08 11:42 UTC, iuravic requested changes

2023-03-08 11:42 UTC, iuravic commented on src/Logic/GutenbergBlockGenerator.php
> +/**
@kariae , woohoo! 🥳

2023-03-08 11:42 UTC, iuravic commented on src/Utils/Logger.php
> +	public function log( $file, $message, $level = 'line' ) {
Since we're changing the number and order of parameters here, this will break backwards compatibility with,
- Command/General/PostsMigrator, [line](https://github.com/Automattic/newspack-custom-content-migrator/blob/master/src/Command/General/PostsMigrator.php#L668)

We can update the PostsMigrator class, but I personally would vote that we kept the `$to_cli = true` param, since I sometimes like not to output to CLI for some very low-level detail logging, and in this case if we kept the existing args and just added the new $level like `log( $file, $message, $to_cli = true, $level = 'line' )` , it would also keep backwards compatibility.

2023-03-08 12:00 UTC, kariae commented on src/Utils/Logger.php
> +	public function log( $file, $message, $level = 'line' ) {
@iuravic sounds logical to me, I just find it redundant to have the level and the CLI, and if you pass `false` as level it won't output to the CLI, so this won't break [this line](https://github.com/Automattic/newspack-custom-content-migrator/blob/master/src/Command/General/PostsMigrator.php#L668), there is a [check before outputting to the CLI](https://github.com/Automattic/newspack-custom-content-migrator/pull/270/files#diff-44097db48bf8d8bbb3d223b2e57d01674e8f63f7ff767bdd226d72248fb14b0bR41)

2023-03-08 13:32 UTC, iuravic commented on src/Utils/Logger.php
> +	public function log( $file, $message, $level = 'line' ) {
Ah, that's right, sorry I missed it.

2023-03-08 13:32 UTC, iuravic approved these changes

2023-03-08 13:33 UTC, merged