Add helper class for "migration meta".
Automattic/newspack-custom-content-migrator pull request #334
Opened 2023-08-31 10:57 UTC by naxoc

Keeping track of commands run and re-run should be easier with this.

2023-08-31 13:52 UTC, iuravic commented on src/Utils/MigrationMeta.php
> +	 * The meta key used to store the migration meta.
Can we update "The meta key used to store the migration meta." to "The meta key used to store the **serialized** migration meta.

2023-08-31 15:23 UTC, iuravic requested changes
A couple of small comments added 🙏

2023-09-01 08:01 UTC, naxoc commented on src/Utils/MigrationMeta.php
> +namespace NewspackCustomContentMigrator\Utils;
Yup! I moved it :)

2023-09-01 12:05 UTC, iuravic approved these changes

2023-09-01 12:46 UTC, merged