Download missing images
Automattic/newspack-custom-content-migrator pull request #340
Opened 2023-09-11 16:29 UTC by naxoc

This downloads missing images and is probably re-usable for other sites in the future.

I pulled most code into a new file because there ended up being a lot of it :)

Run it with `wp newspack-content-migrator la-silla-vacia-download-missing-images --media-dir="../path/to/medi" --post-id=5325` and post id is optional.

2023-09-11 16:58 UTC, eddiesshop requested changes
Super clean and efficient! Just 2 very small things and I think we're good to go!

2023-09-11 16:58 UTC, eddiesshop commented on src/Command/General/DownloadMissingImages.php
> +
Can we please log any files that are moved?

2023-09-11 16:58 UTC, eddiesshop commented on src/Command/General/DownloadMissingImages.php
> +			MigrationMeta::update( $data['post']->ID, $this->command_meta_key, 'post', $this->command_meta_version ); // TODO
Not a big deal, but is this TODO still relevant?

2023-09-11 21:38 UTC, naxoc commented on src/Command/General/DownloadMissingImages.php
> +
Yup! I added that

2023-09-11 21:39 UTC, naxoc commented
I added one more arg to be used like this: `--post-id-range=1000-20000"` so we can run post id ranges.

2023-09-17 23:17 UTC, eddiesshop commented
Tested this out on a few posts and it's working great! Thank you for all this hard work!

2023-09-17 23:17 UTC, eddiesshop approved these changes

2023-09-17 23:17 UTC, merged