Town News: Try to avoid using email as display name for authors
Automattic/newspack-custom-content-migrator pull request #374
Opened 2023-11-03 16:21 UTC by naxoc

I noticed that we can risk creating slugs with emails. This does some string juggling to avoid that.

## How to test
- Run the migration and verify that guest users are created with whatever is before the '@' if there is only an email on them.

2023-11-08 10:34 UTC, kariae requested changes

2023-11-08 10:34 UTC, kariae commented on src/Command/General/TownNewsMigrator.php
> +			$guest_author = $this->coauthorsplus_logic->get_guest_author_by_user_login( $display_name );
Using `$email` was a bug here, nice catch! The [create_guest_author](https://github.com/Automattic/newspack-custom-content-migrator/blob/ea5e7a66d1c0727230936284059fbd9e68657519/src/Logic/CoAuthorPlus.php#L105) used [here](https://github.com/Automattic/newspack-custom-content-migrator/pull/374/files#diff-a630c53224b300be80052c56980d3a5f4a5d0ed96e9764671318e1fa9010aaa7R714) to create a new co-author uses the sanitized display_name as user_login in case we don't provide the later, so I think to fetch co-authors using `$display_name` as user_login we should pass the sanitized version.
```suggestion
			$guest_author = $this->coauthorsplus_logic->get_guest_author_by_user_login( sanitize_title( $display_name ) );
```

2023-11-10 09:47 UTC, naxoc commented on src/Command/General/TownNewsMigrator.php
> +			$guest_author = $this->coauthorsplus_logic->get_guest_author_by_user_login( $display_name );
Thanks Zak - good catch! 

I added sanitization with sanitize_user because I assume that is what the user login is run through when it's created. Does that make sense?

2023-11-10 09:47 UTC, naxoc commented
I also added tag stripping in bylines – I had a couple of files where the byline was dirty.

2023-11-10 09:50 UTC, kariae commented on src/Command/General/TownNewsMigrator.php
> +			$guest_author = $this->coauthorsplus_logic->get_guest_author_by_user_login( $display_name );
The user is created as of now with [`sanitize_title`](https://github.com/Automattic/newspack-custom-content-migrator/blob/ea5e7a66d1c0727230936284059fbd9e68657519/src/Logic/CoAuthorPlus.php#L112), but I think it's better to fix it properly and change it there to `sanitize_user`

2024-01-08 16:27 UTC, naxoc commented
@kariae This one got a bit old. I'm not sure if it is still relevant. What do you think?

2024-05-08 07:43 UTC, naxoc commented
@kariae I think this one can just be closed with no merge. It's so old :) What do you think?

2024-06-21 15:55 UTC, kariae approved these changes
LGTM!

2024-07-05 10:38 UTC, merged