Feat/guest author validation refactor
Automattic/newspack-custom-content-migrator pull request #434
Opened 2024-02-12 18:38 UTC by eddiesshop

## How to test

- Grab a DB export from LSV from or before December.
- Run `wp newspack-content-migrator la-silla-vacia-validate-guest-authors`
- You can kill the script after a few dozen validation errors.
- Looking at the data that is output, find a standalone Guest Author (i.e. one that has an empty `cap-linked_account`, or simply one GA that doesn't show any WP_User data in the output)
- Using the `wp_posts.id`/Guest Author ID and `wp_terms.term_id`/Author Taxonomy ID, run `wp newspack-content-migrator co-authors-set-standalone-guest-author-data --guest-author-id=<guest-author-id> --term-id=<term-id>`. Notice the output, and what data has been changed/updated.

Another way to test this is:
- Create a GA on a test site.
- Add or remove `cap-*` related data from `wp_postmeta` for that GA
- Modify the GA's `wp_terms`/`wp_term_taxonomy` record by updating the slug or description, etc.
- Can you assign that GA to a post? What happens when you publish that post? Is a new Term created?
- After running `wp newspack-content-migrator co-authors-set-standalone-guest-author-data --guest-author-id=<guest-author-id> --term-id=<term-id>`, does the same thing happen when you assign that GA to a post?

---

- [X] confirmed that PHPCS has been run

2024-02-13 08:19 UTC, iuravic requested changes
Since this is a new, independent and self supporting functionality let's refactor and move it's belonging code into its own place to live, separated and uncluttered by other functionality. I think it definitely merits its own class. That way it can both be tested and used more clearly, updated and even refactored as independent functionality if needed.

- move all code added to `src/Command/General/CoAuthorPlusMigrator.php` into a new command class `src/Command/General/CoAuthorPlusDataFixer.php` (or similar name)
- also move following methods from `Logic\CoAuthorPlus` to the new command class:
  - `attempt_to_relate_standalone_guest_author_and_term`
  - `insert_guest_author_taxonomy`
  - `get_author_term_description`
  - `update_author_term_description`
  - `is_guest_author_standalone`
  - `get_cap_fields`
  - `get_filtered_cap_fields `
- move code from `src/Logic/Posts.php` to new command -- concerns display used only by the command
- move following code from `src/Logic/Taxonomy.php` into new command class
  - `output_term_and_term_taxonomy_table`
  - `output_term_taxonomy_table`
- move all code from `src/Logic/User.php` to new command class -- code just for specific kind of display used by this functionality, not logic 

Make sure to run PHPCS on all this code, including:
- add proper docblocks to all @return array and object, explaining elements/properties being returned

2024-04-30 13:02 UTC, iuravic approved these changes
Everything looks good to me security wise 👍 I haven't had the chance to test run it but approving so that it can be used where necessary.

2024-04-30 13:34 UTC, jorostoyanov commented
Looks good to me as well 🚀 Thank you!

2024-05-07 19:59 UTC, eddiesshop commented on src/Logic/CoAuthorPlusDataFixer.php
> +		return $this->get_guest_author_taxonomy( $term_id )[0]->term_taxonomy_id;
Hrmm, this will return an int right? What's doing is calling `get_guest_author_taxonomy` which returns an array of objects. I'm getting that first object in the array and then returning the int `term_taxonomy_id`. Nonetheless I added an explicit `intval` call just to be safe.

2024-05-07 20:05 UTC, eddiesshop commented on src/Logic/CoAuthorPlusDataFixer.php
> +		return array_map(
Thanks! Went ahead and implemented this suggestion.

2024-05-07 20:47 UTC, eddiesshop commented on src/Logic/CoAuthorPlusDataFixer.php
> +	 * @return int|WP_Error
Made it so that PHP matches docblock return type

2024-05-07 21:06 UTC, eddiesshop commented on src/Logic/CoAuthorPlusDataFixer.php
> +	 * @return int|WP_Error
Updated PHP to match Docblock

2024-05-07 21:13 UTC, eddiesshop commented on src/Logic/ConsoleOutput/Taxonomy.php
> +	 * @return array
Updated documentation to reflect what's actually being returned, an array of stdClass objects.

2024-05-07 21:13 UTC, merged