Remove unused files
Automattic/newspack-custom-content-migrator pull request #549
Opened 2024-10-16 10:12 UTC by naxoc

Also clean up references to a file that was moved a while ago (the JsonIterator).

The mustache stuff was never used and the PHP.php file had no usages either.

2024-10-16 14:38 UTC, jorostoyanov requested changes
@naxoc Found one duplicate line and the PHP util class is still being used.

The rest looks good :)

2024-10-16 14:38 UTC, jorostoyanov commented on publisher-specific-archive/LaSillaVaciaMigrator.php
> +					'name'     => 'Red Paisa',
There is a duplicate line here :)

2024-10-16 14:38 UTC, jorostoyanov commented on src/Utils/PHP.php
I see this being used in `src/Command/General/S3UploadsMigrator.php`.

2024-10-21 10:21 UTC, naxoc commented on src/Utils/PHP.php
Great catch. I removed the usage

2024-10-21 11:50 UTC, merged